name: Run test and record test coverage reports

on:
  workflow_call:

jobs:
  prep_unit-test:
#    name: Prepare all unit test items
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_get_tests.yaml@v7.2
    with:
      shell_arg: test/unit_test/

  run_unit-test:
#    name: Run all unit test items
    needs: prep_unit-test
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_poetry_run_test.yaml@v7.2
    with:
      runtime_os: ubuntu-latest
      python_version: '3.12'
      test_type: unit-test
      all_test_items_paths: ${{needs.prep_unit-test.outputs.all_test_items}}

  unit-test_codecov:
#    name: For unit test, organize and generate the testing report and upload it to Codecov
    if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_name == 'master') }}
    needs: run_unit-test
    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_organize_test_cov_reports.yaml@v7.2
    with:
      test_type: unit-test
