#################################################################################################################################
#
# Workflow Description:
#     Use Poetry to run testing by specific type with all test items via PyTest and generate its testing
#     coverage report (it would save reports by 'actions/upload-artifact').
#
# Workflow input parameters:
#     * runtime_os: The OS to use for runtime environment. In default, it's 'ubuntu-latest'.
#     * python_version: The Python version to run the workflow. In default, it's Python version '3.11'.
#     * test_type: The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'.
#     * test_working_directory: The working directory for test running.
#     * install_dependency_with_group: Install the dependency by Poetry configuration with dependency group setting. This parameter receive the dependency group naming.
#     * install_dependency_without_group: Install the dependency by Poetry configuration without dependency group setting. This parameter receive the dependency group naming.
#     * all_test_items_paths: The target paths of test items under test.
#     * setup_http_server: If it's true, it would set up and run HTTP server for testing.
#     * http_server_host: The host IPv4 address of HTTP server.
#     * http_server_port: The port number of HTTP server.
#     * http_server_app_module: The module path of HTTP server.
#     * http_server_enter_point: The object about the web application.
#     * keep_run_if_test_fail: Keep running CI process if it gets failure at running runs.
#
# Workflow running output:
#     No, but it would save the testing coverage reports to provide after-process to organize and record.
#
#     * Upload-Artifact:
#         * coverage: The test coverage report which be generated by PyTest, and it's recorded after run test done.
#                           The file name format would be .coverage.<test type>.<runtime os>-<python-version>
#
#################################################################################################################################

name: Run test items via PyTest

# TODO: Run Python package test via Poetry.

on:
  workflow_call:
    inputs:
      runtime_os:
        description: "The OS to use for runtime environment. In default, it's 'ubuntu-latest'."
        required: false
        type: string
        default: ubuntu-latest
      python_version:
        description: "The Python version to run the workflow. In default, it's Python version '3.11'."
        required: false
        type: string
        default: 3.11
      test_type:
        description: "The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'."
        required: true
        type: string
      test_working_directory:
        description: "The working directory for test running."
        required: false
        type: string
        default: './'
      install_dependency_with_group:
        description: "Install the dependency by Poetry configuration with dependency group setting. This parameter receive the dependency group naming."
        type: string
        required: false
        default: ''
      install_dependency_without_group:
        description: "Install the dependency by Poetry configuration without dependency group setting. This parameter receive the dependency group naming."
        type: string
        required: false
        default: ''
      all_test_items_paths:
        description: "The target paths of test items under test."
        required: true
        type: string
      setup_http_server:
        description: "If it's true, it would set up and run HTTP server for testing."
        type: boolean
        required: false
        default: false
      http_server_host:
        description: "The host IPv4 address of HTTP server."
        type: string
        required: false
        default: 0.0.0.0
      http_server_port:
        description: "The port number of HTTP server."
        type: string
        required: false
        default: 12345
      http_server_app_module:
        description: "The module path of HTTP server."
        type: string
        required: false
        default: app
      http_server_enter_point:
        description: "The object about the web application."
        type: string
        required: false
        default: app
      keep_run_if_test_fail:
        description: "Keep running CI process if it gets failure at running runs."
        type: boolean
        required: false
        default: false

# TODO: Add a reusable workflow about running test via Poetry
# TODO: https://github.com/marketplace/actions/python-poetry-action

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  run_test_items:
    runs-on: ${{ inputs.runtime_os }}

    strategy:
      matrix:
        test-path: ${{fromJson(inputs.all_test_items_paths)}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Python dependencies
        run: |
          pip --version
          pip install -U flask
          pip install -U gunicorn
          pip install -U poetry
          poetry --version

      - name: Build Python runtime environment by Poetry
        if: ${{ inputs.install_dependency_with_group == '' && inputs.install_dependency_without_group == '' }}
        working-directory: ${{ inputs.test_working_directory }}
        run: |
          pwd
          ls -la
          poetry install

      - name: Build Python runtime environment by Poetry with dependency group *${{ inputs.install_dependency_with_group }}*
        if: ${{ inputs.install_dependency_with_group != '' }}
        working-directory: ${{ inputs.test_working_directory }}
        run: |
          poetry install --with=${{ inputs.install_dependency_with_group }}

      - name: Build Python runtime environment by Poetry without dependency group *${{ inputs.install_dependency_without_group }}*
        if: ${{ inputs.install_dependency_without_group != '' }}
        working-directory: ${{ inputs.test_working_directory }}
        run: |
          poetry install --without=${{ inputs.install_dependency_without_group }}

      - name: Setup and run HTTP server for testing
        if: ${{ inputs.setup_http_server == true }}
        working-directory: ${{ inputs.test_working_directory }}
        run: gunicorn --bind ${{ inputs.http_server_host }}:${{ inputs.http_server_port }} '${{ inputs.http_server_app_module }}:${{ inputs.http_server_enter_point }}' --daemon

      - name: Test to send HTTP request to sample HTTP server
        if: ${{ inputs.setup_http_server == true }}
        run: curl "http://${{ inputs.http_server_host }}:${{ inputs.http_server_port }}/exchangeReport/STOCK_DAY?response=json&date=20170101&stockNo=2331"

      - name: Run tests with pytest
        working-directory: ${{ inputs.test_working_directory }}
        run: poetry run pytest ${{ matrix.test-path }}
        continue-on-error: ${{ inputs.keep_run_if_test_fail }}

      - name: Rename the code coverage result file
        working-directory: ${{ inputs.test_working_directory }}
        run: |
          mv ./.coverage ./.coverage.${{ inputs.test_type }}.${{ inputs.runtime_os }}-${{ inputs.python_version }}

      - name: Upload code coverage result file
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test_type }}_${{ inputs.runtime_os }}_${{ inputs.python_version }}
          path: ${{ inputs.test_working_directory }}.coverage.${{ inputs.test_type }}.${{ inputs.runtime_os }}-${{ inputs.python_version }}
          if-no-files-found: error
          include-hidden-files: true
